PSFzf.psm1, README.md
Ctrl+R uses fzf instead of calling the
ReverseSearchHistory command in
PSReadline
=> PSReadline history search

PSFzf.Functions.ps1, docs/Set-LocationFuzzyEverything.md
Make Search-Everything only search for directories: this is faster and
avoids errors when selecting a file from the matches since these cannot
be cd'ed to anyway.
Also add a directory argument for selecting the initial directory (this eventually
uses Everything's `path:` so can be used to specify starting directory or partial match),
making it more versatile as it allows starting the search in another directory than the
current one and makes it a much faster alternative to Invoke-FuzzySetLocation.
For a directory with about 10000 subdirectories, `cde somedir` is instant while `fd somedir` takes 10 seconds.
=> Fix usage of Search-Everything for setting location

PSFzf.psm1
If a user has chosen to ignore duplicates in the Psreadline history,
apply this to the history shown by Invoke-FzfPsReadlineHandlerHistory as
well for consistency since it will usually used in place of the original
PsReadLine hisotroy search.
Note that PsReadLine ignores duplicates in code, not in the file it saves,
so we must do the same by filtering duplicates from the file.
Note I replaces some spaces with tabs in this function to keep things readable.
=> Respect PsReadline's HistoryNoDuplicates setting

PSFzf.Functions.ps1, docs/Invoke-FuzzyEdit.md
This allows 'Invoke-FuzzyEdit <some/dir>' without having to manually cd
to the wanted directory first.
=> Add Directory argument for Invoke-FuzzyEdit

PSFzf.psm1
Select-Object -Unique walks the input from top to bottom, which means
if we put in @(a, b, c, a) the output is @(a, b, c). This is unwanted
here because we're listing history and want the most recent commands to
turn up first, and in this case 'first' means at the bottom of the list;
in other words we want @(b, c, a) as output.
Fix this by reversing the history lines before removing duplicates.
=> Fix sort order when listing history without duplicates

PSFzf.psm1, ReverseLineReader.cs
CTRL+R reads latest history first. This means that 
latest history is shown immediately. Also, duplicates
are not shown in the history.
=> Default reverse history

.gitignore
I'm installing the tool using git submodules, and I build it if I need it, but the directory shows dirty because PSFzf.dll is not ignored. Adding this allows this workflow to work.
=> Ignore PSFzf.dll on root

PSFzf.psm1
- Tells PSReadLine to redraw prompt after Invoke-Fzf is executed
- resolves #37
=>  Workaround for missing PSReadLine prompt

PSFzf.TabExpansion.ps1
- combine multiple results into a single string
- invoke fzf by itself if no results are returned from Expand-GitCommand
- add InvokePrompt workaround after fzf is invoked
=> Tab expansion improvements

README.md
Changes usage for faster option:
PS C:\Users\drubio> Compare-Object ( Get-ChildItem . -Recurse -Attributes "Directory" ) ( Get-ChildItem . -Recurse | ? { $_.PSIsContainer } )
PS C:\Users\drubio> Measure-Command { Get-ChildItem . -Recurse | ? { $_.PSIsContainer } }
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 15
Milliseconds      : 861
Ticks             : 158618315
TotalDays         : 0.000183586012731481
TotalHours        : 0.00440606430555556
TotalMinutes      : 0.264363858333333
TotalSeconds      : 15.8618315
TotalMilliseconds : 15861.8315
PS C:\Users\drubio> Measure-Command { Get-ChildItem . -Recurse -Attributes "Directory" }
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 6
Milliseconds      : 122
Ticks …
=> Updates readme.md

PSFzf.Functions.ps1
- Invoke-FuzzyHistory uses PSReadLine history, if available
- Resolves #47
=> Use PSReadLine history

helpers/PsFzfTabExpansion-Preview.ps1
without the quotes, bat interprets "changes" as a name of a file and displays an error (at least on my machine)
=> Fixed bat command

PSFzf.Base.ps1
Working directory was not getting set correctly as this condition was always false. We need to compare the `Name` property of Provider.
Tested on Windows, Linux and macOS.
Closes #65
=> Fix working directory condition

PSFzf.Functions.ps1
join-path replaced with resolve-path to handle absolute or relative paths.
dir outputs absolute paths while find/fd output relative paths.
also fixed $files check for Count instead of $null, because
the variable is instantiated as an empty array and therefore
isn't $null
Closes #99
=> fix: invoke-fuzzyedit directory resolve

PSFzf.Base.ps1
Exception during stream flush would abort the pipeline and fail to
properly process any result of selection when using Alt+c or Ctrl+t
functionality, for example.
This *will* happen on Linux when accepting the selection early, before
the earlier step finishes streaming input and if it is a system command
rather than powershell cmdlet.
Fixes #112.
=> Do not abort when failing to flush a stream

PSFzf.Base.ps1
Default Windows command quotes path argument in the constant. Default
Linux command does not. Default fd commands do not quote argument in the
constants but instead transform path string given to Get-FileSystemCmd.
This unifies the situation so that all constants have path argument
quoted and no additional processing is thus required in
Get-FileSystemCmd.
Fixes #116.
=> Consistenly quote path argument in default commands

PSFzf.Base.ps1, PSFzf.Functions.ps1
Console :
- Activate ANSI Compatibility (WindowsTerminal) when using ConEmu ( https://github.com/Maximus5/ConEmu )
FuzzyEdit : 
Maybe somes options are very specific for my use 
- FuzzyEdit Directly open File when arguments is a file 
- Default editor can be set in env EDITOR ou env VISUAL
- Allow user to pass options to editor 
ex : Vim allow to open multiple files in Tab (-p), HSplit (-o), VSplit (-O)
=> Ansi Console support And FuzzyEdit

PSFzf.Functions.ps1, README.md
- rename ps var to env var
- update readme.md
- fix bug with editor options str concat
=> Minor fixes

PSFzf.Functions.ps1
- Invoke-FuzzyGitStatus calls Invoke-PsFzfGitFiles, which does the same
thing except it displays a preview window
- Resolves #143
=> Invoke-FuzzyGitStatus -> Invoke-PsFzfGitFiles

PSFzf.Base.ps1, PSFzf.tests.ps1
- FixCompletionResult will use double quotes to quote string instead of single in case file name as a single quote in the name
- Add unit tests for FixCompletionResult
- Resolves #171
=> Use Double quotes instead of single

PSFzf.Git.ps1
There was a little typo in the description of the PSReadlineKeyHandler for getting the stashes. It probably just comes from a quick copy paste of the previous line.
=> ✏️ Name properly the PSReadLineKeyHandler for stashes

PSFzf.Base.ps1
Nowadays, the default method of sorting in fzf when pressing <kbd>Ctrl+r</kbd> is by relevance and not chronological order ([c387689](https://github.com/junegunn/fzf/commit/c387689d1cd45f0d8eb122fe95ee72ccc61d3bff)). If the user wishes to see the commands in chronological order they must either press <kbd>Ctrl+r</kbd> again or add `--no-sort` to `FZF_CTRL_R_OPTS`.
The function `Invoke-FzfPsReadlineHandlerHistory()` currently passes the `-NoSort` argument whenever it is called, thus making fzf always sort by chronological order, even if we add `--sort` to `FZF_CTRL_R_OPTS`. I propose this argument should be removed, letting the user decide, by adding or not `--no-sort` to `FZF_CTRL_R_OPTS`, how they wish to order their results and making PSFzf's default behavior equal to fzf's.
=> Make sorting by relevance the default behavior

PSFzf.Git.ps1
I used `scoop` to install `git` (and `fzf` and `PSFzf`) but since it uses shims it seems that `PSFzf` is unable to find `bash` and `grep` for the `git` key bindings.
I quickly hacked together a simple fix that should work in most cases (for example when `scoop` is not installed at the default location).
I built it and tested the fix on my computer and it should be working fine.
=> ✨ Handle a scoop installation of git

PSFzf.Git.ps1
- Git functions update prompt in keyboard shortcuts, and return strings
when run as functions
- Should resolve #191
=> Git functions return text instead update prompt

helpers/PsFzfTabExpansion-Preview.ps1
- better check if git doesn't exist
- output git status at the bottom instead of the top
- use bat, if found, to output git status
-  resolves the issue mentioned in #213
=> tab complete enhancements

PSFzf.Functions.ps1
- Invoke-FuzzySetLocation no longer uses FZF_DEFAULT_COMMAND to ensure
proper directory selection
- Fixes #229
=> Don't use FZF_DEFAULT_COMMAND

README.md
Change PSEverything URL to point to the PSEverything repository, to be consistent with the other links.
=> Change PSEverything URL to point to repository.

PSFzf.Functions.ps1
- $env:EDITOR and $ENV:VISUAL are now respected properly if the editor is unknown
- Resolves #246
- Tested with `$env:EDITOR=notepad`
=> Get-EditorLaunch returns a cmd line for unknown editor

PSFzf.Base.ps1, PSFzf.Functions.ps1
- Invoke-FuzzyHistory() (alis: 'fh') now removes duplicates
- Resolves #219
=> Refactor history retrieval and handling

PSFzf.Base.ps1
=> Use the built-in walker, if available

PSFzf.Base.ps1, PSFzf.Functions.ps1, PSFzf.Git.ps1
- Resolves #273 
- Add 'Disabled' param
- Restore unicode icons for git functions and only show in Terminal or non-Windows
- Minor formatting fix
=> Fix `Invoke-PsFzfRipgrep` throws `unknown action: change-prompt` after updating to 2.6.1 #273

PSFzf.Git.ps1
=> Properly detect if git is installed using scoop regardless of scope

PSFzf.Base.ps1
This PR fixes `--walker` options specified in either `_PSFZF_FZF_DEFAULT_OPTS` or `FZF_DEFAULT_OPTS` being overridden with `--walker=file,dir` defined in `Invoke-FzfDefaultSystem` function.
=> Fix being unable to override walker opts when not using "fd"

PSFzf.Base.ps1
see issue https://github.com/kelleyma49/PSFzf/issues/297
=> fix: revert RunningInWindowsTerminal typo error

PSFzf.Git.ps1
Explicitly set the [`-BriefDescription`](https://learn.microsoft.com/en-us/powershell/module/psreadline/set-psreadlinekeyhandler#-briefdescription) parameter of [`Set-PSReadLineKeyHandler`](https://learn.microsoft.com/en-us/powershell/module/psreadline/set-psreadlinekeyhandler) to something descriptive when creating each Git key binding.
This additional metadata makes the output of [`Get-PSReadLineKeyHandler`](https://learn.microsoft.com/en-us/powershell/module/psreadline/get-psreadlinekeyhandler) and [`[Microsoft.PowerShell.PSConsoleReadLine]::ShowKeyBindings`](https://learn.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline_functions#showkeybindings) (i.e. `Ctr+Alt+?`) more useful, particularly when there is a number of key handlers the user is searching through. …
=> GitKeyBindings BriefDescription

.github/workflows/CI.yml, .github/workflows/Deploy.yml
Eliminate the FZF_VERSION environment variable from the CI and Deploy workflows to streamline the setup process.
=> Remove FZF_VERSION from CI and Deploy workflows

PSFzf.Base.ps1
* This is an attempt to fix #340
=> Fix handling of empty strings in Invoke-FzfPsReadlineHandlerProvider

PSFzf.psd1
The following code is about lazy loading psfzf
```ps1
function LazyImportPSFzf {
Set-PsFzfOption -EnableFd -EnableAliasFuzzyScoop
}
Set-PSReadLineKeyHandler -ViMode Insert -Key Ctrl+t -ScriptBlock {
if ((Get-Module -Name PSFzf) -eq $null) { LazyImportPSFzf }
Invoke-FzfPsReadlineHandlerProvider
}
Set-PSReadLineKeyHandler -ViMode Insert -Key Ctrl+r -ScriptBlock {
if ((Get-Module -Name PSFzf) -eq $null) { LazyImportPSFzf }
Invoke-FzfPsReadlineHandlerHistory
}
Set-PSReadLineKeyHandler -ViMode Insert -Key Alt-c -ScriptBlock {
if ((Get-Module -Name PSFzf) -eq $null) { LazyImportPSFzf }
Invoke-FzfPsReadlineHandlerSetLocation
}
Set-PSReadLineKeyHandler -ViMode Insert -Key Alt-a -ScriptBlock {
if ((Get-Module -Name PSFzf) -eq $null) { LazyImportPSFzf }
Invoke-FzfPsReadlineHandlerHistoryArgs
}
```
=> Export Invoke-FzfPsReadlineHandler* thus lazy loading could be possible
