PSFzf.Functions.ps1
PSFzf.psd1
README.md
docs/Invoke-FuzzyZLocation.md
en-US/about_PSFzf.help.txt

I've been using this function myself for a while and it seems handy enough for use by others as well so here's a PR.

Add helper function for invoking fzf on ZLocation's history

---

.github/scripts/Install.ps1
.github/workflows/CI.yml
.github/workflows/Deploy.yml
PSFzf.Functions.ps1
PSFzf.psm1
PSFzf.tests.ps1

- add KeepRight, Height, MinHeight, BorderStyle, Pointer, and Marker cmd
line options
- add tests to test parameter validation
- turn height on if running in Windows Terminal
- small code cleanup
- add header to ```fkill``` shortcut

Add new cmd line arg forwarding

---

PSFzf.TabExpansion.ps1

Fix to work with posh-git 1.0

---

PSFzf.Functions.ps1
PSFzf.TabExpansion.ps1
PSFzf.psd1
PSFzf.psm1

- experimental support for fzf trigger tab completion
- works with *-Process and *-Service commands
- add Set-PsFzfOptions command

Tab completion & Set-PsFzfOptions command

---

PSFzf.psm1

This commit changes the Invoke-Fzf function to send UTF-8 encoded text
to the fzf process and read UTF-8 encoded text from stdout. Without this
change, non-ASCII characters would not be handled correctly. For
example:
$ echo '360°' | Invoke-Fzf
360∩┐╜
$ echo '360°' | fzf
360°
After the change:
$ echo '360°' | Invoke-Fzf
360°
Signed-off-by: Andrew Gunnerson <chillermillerlong@hotmail.com>

Invoke-Fzf: fzf expects stdin/stdout encoding to be UTF-8

---

PSFzf.Base.ps1

Use partial history to initiate search

---

.editorconfig
.vscode/tasks.json

- set tab size so GitHub respects # of spaces for tabs
- update vscode tasks file format

Minor repo cleanup

---

PSFzf.Base.ps1
README.md

- If set, PSFZF will use the contents of this env variable instead
FZF_DEFAULT_OPTS

Support _PSFZF_FZF_DEFAULT_OPTS (#89)

---

PSFzf.Base.ps1
PSFzf.Functions.ps1
PSFzf.TabExpansion.ps1

Hello,
Issue Request to correct problem when psFZF is invoke from networkshare

Replace $pwd.Path with $pwd.ProviderPath

---

PSFzf-Binary/CompletionHelpers.cs

Change GetUnambiguousPrefix() to be case sensitive

---

PSFzf.TabExpansion.ps1

Fix tab expansion to work with Windows PowerShell

---

.github/scripts/Install.ps1
.github/scripts/Tests.ps1
.vscode/settings.json
PSScriptAnalyzerSettings.psd1

- Run PSScriptAnalyzer in github actions
- Fix capitalization
- Move analyzer settings to file

move analyzer files to file

---

PSFzf.Base.ps1

Alt+C didn't really work with default commands unless fd was enabled,
because other default filesystem commands didn't know how to show
directories only and showed files instead.
In particular, FZF_DEFAULT_COMMAND cannot be used with dirOnly as you
never know what's there and how to adapt it. The script defaults now
have a dirOnly versions as well.
Additionally, find needs to at least follow symbolic links. Otherwise,
it cannot say if they should count as files or directories which leads
to being unable to switch to a directory that is a link, or showing
links to directories as file input which is not what you expect to
happen in such situations on Linux.
Fixes #114.

Get-FileSystemCmd should honour dirOnly

---

PSFzf.Base.ps1

Allow multi select for history args cmd

---

PSFzf.Base.ps1

Add -AltCCommand for Set-PsFzfOption

---

PSFzf.TabExpansion.ps1

- don't use PrintQuery as I'm getting unexpected output ordering under
Powershell 5

Resolve #85

---

PSFzf.TabExpansion.ps1
helpers/PsFzfTabExpansion-Parameter.ps1

- Check if completion is a a parameter and use Get-Help to output parameter information
- Check if parameter is a common parameter and output help for common parameter
- Resolves #96

Add support for parameter completion

---

PSFzf.TabExpansion.ps1

Remove embarrassing debug output

---

PSFzf.TabExpansion.ps1

- Resolves #142 
- I broke this in #119
- copied from https://github.com/pitkali/PSFzf/commit/5df5fb316ace1fd2d33388453d5ff7b500b5608c - thanks @pitkali!

Fix bug in handling of continuous trigger

---

PSFzf.Functions.ps1
PSFzf.Git.ps1
PSFzf.TabExpansion.ps1
helpers/GetProcessesList.ps1

- enhanced process selection which almost matches https://github.com/junegunn/fzf/blob/master/ADVANCED.md#updating-the-list-of-processes-by-pressing-ctrl-r
- make keyboard help commands more consistent

Enhanced Process Selection

---

PSFzf.Base.ps1
PSFzf.Functions.ps1
PSFzf.TabExpansion.ps1

- Work under Windows PowerShell 5

Fix for new process selection

---

PSFzf.Functions.ps1
README.md
docs/Invoke-PsFzfRipgrep.md

- Add documentation for Invoke-PsFzfRipgrep
- Add -NoEditor parameter
- Use FzfLocation instead of fzf.exe (doesn't work on other platforms)

Add documentation for Invoke-PsFzfRipgrep

---

PSFzf.Functions.ps1

Supports for nvim, gvim and nano.

Add gvim, nvim and nano as editor

---

PSFzf.Base.ps1

- Use built-in directory walking if fd is not used

Use built-in directory walking

---

PSFzf.Base.ps1
PSFzf.Functions.ps1
PSFzf.TabExpansion.ps1

- Resolves #154
- Use array version of Bind

Bind parameter is now an array

---

PSFzf.Git.ps1

- Git functions work on Linux (Mac untested)
- Invoke-FuzzyGitStatus should work without adding git key bindings (should resolve #163)

Git functions work on Linux

---

PSFzf.Git.ps1

- resolves #162
- remove debug output left from previous commit

Workaround for file path

---

.editorconfig
PSFzf.psd1

- Add Invoke-PsFzfGitBranches to exported functions
- Resolves #156

Add Invoke-PsFzfGitBranches to exports

---

PSFzf.TabExpansion.ps1

Catch CompleteInput() exceptions

---

PSFzf.TabExpansion.ps1

- ESC key cancels and won't tab complete anything

Hande ESC properly

---

PSFzf.TabExpansion.ps1

- Remove query prefix as it made search results filtering more
restrictive

Remove query prefix

---

PSFzf.TabExpansion.ps1

Remove unused code

---

PSFzf.Base.ps1
PSFzf.Git.ps1
PSFzf.psd1
helpers/PSFzfGitBranches.ps1
helpers/PsFzfGitBranches-Preview.sh
helpers/PsFzfGitBranches.sh
helpers/PsFzfGitFiles-Preview.sh

- Minor cleanup
- Add -Color argument
- Use Fzf common parameters
- Correct prompt argument
- Set prompts
- Color arg is passed correctly
- Correctly quote arguments to fzf
- Branch matches fzf-git
- More work to mirror fzf-git

Make git functions more similiar to fzf-git

---

PSFzf.Functions.ps1
PSFzf.Git.ps1

- Fixes failures when PSFzf is installed in a directory that contains
spaces in its name

Add quotes to helper scripts

---

PSFzf.TabExpansion.ps1

Tab expansion preview to bottom

---

PSFzf.Base.ps1
PSFzf.Functions.ps1
PSFzf.Git.ps1
helpers/PsFzfTabExpansion-Preview.ps1

- Prevents adding messages to $Error`

Use Ignore instead of SilentlyContinue

---

PSFzf.Git.ps1

Add Ctrl-a shortcut for git branches

---

PSFzf.Base.ps1

Small fix to address that issue - https://github.com/kelleyma49/PSFzf/issues/133.

Added binding for Vim command mode

---

PSFzf.Base.ps1
PSFzf.Git.ps1

- Add -BorderLabel support
- Add missing BorderStyles

Use BorderLabel instead of Prompt for git commands

---

PSFzf.Base.ps1
PSFzf.Functions.ps1

- Add Scheme option
- Use Scheme option in history functions
- Resolves #211

Set Scheme for history functions

---

PSFzf.TabExpansion.ps1

Works with git aliases

---

PSFzf.Base.ps1

- Add path used to filter selections to results

Mitigate #236

---

PSFzf.Functions.ps1

Quote file path for nano editor

---

PSFzf.Base.ps1
PSFzf.Functions.ps1

- Also add CTRL-Z for history
- Resolves #240

Remove -NoSort from history commands

---

PSFzf.Git.ps1

- Check for visualstudio domains as well

Fix Azure DevOps PR preview command

---

PSFzf.Git.ps1

- Works for GitHub and ADO
- Checks can be rerun in ADO
- PR selection initially starts with current user, but is selectable with a keyboard shortcut to list all users

Add check viewing support

---

PSFzf.Functions.ps1

Restore default command before editor launch

---

PSFzf.TabExpansion.ps1

- Allows a more continuous tab completion experience
- Resolves #259

Add directory separator to end of completed path

---

PSFzf.Base.ps1
PSFzf.Functions.ps1
PSFzf.TabExpansion.ps1

- Add TabContinuousTrigger parameter and refactor Invoke-FzfTabCompletionInner for improved tab completion handling
- Resolves #300

Add TabContinuousTrigger parameter and refactor Invoke-FzfTabCompletionInner for improved tab completion handling

---

PSFzf.Base.ps1

Support multi-line entries in PSReadline history
